/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  TdpCkanListingType,
} from './components/tdp-ckan-listing/tdp-ckan-listing';

export namespace Components {
  interface TdpCkanConnector {
    /**
    * the url to the CKAN site
    */
    'site': string;
  }
  interface TdpCkanDataset {
    /**
    * The ID of the CKAN dataset
    */
    'datasetId': string;
  }
  interface TdpCkanListing {
    /**
    * The compatible listing type
    */
    'type': TdpCkanListingType;
  }
}

declare global {


  interface HTMLTdpCkanConnectorElement extends Components.TdpCkanConnector, HTMLStencilElement {}
  var HTMLTdpCkanConnectorElement: {
    prototype: HTMLTdpCkanConnectorElement;
    new (): HTMLTdpCkanConnectorElement;
  };

  interface HTMLTdpCkanDatasetElement extends Components.TdpCkanDataset, HTMLStencilElement {}
  var HTMLTdpCkanDatasetElement: {
    prototype: HTMLTdpCkanDatasetElement;
    new (): HTMLTdpCkanDatasetElement;
  };

  interface HTMLTdpCkanListingElement extends Components.TdpCkanListing, HTMLStencilElement {}
  var HTMLTdpCkanListingElement: {
    prototype: HTMLTdpCkanListingElement;
    new (): HTMLTdpCkanListingElement;
  };
  interface HTMLElementTagNameMap {
    'tdp-ckan-connector': HTMLTdpCkanConnectorElement;
    'tdp-ckan-dataset': HTMLTdpCkanDatasetElement;
    'tdp-ckan-listing': HTMLTdpCkanListingElement;
  }
}

declare namespace LocalJSX {
  interface TdpCkanConnector {
    /**
    * the url to the CKAN site
    */
    'site'?: string;
  }
  interface TdpCkanDataset {
    /**
    * The ID of the CKAN dataset
    */
    'datasetId'?: string;
  }
  interface TdpCkanListing {
    /**
    * Emitted when a user selects a new item from the list
    */
    'onItemSelected'?: (event: CustomEvent<any>) => void;
    /**
    * The compatible listing type
    */
    'type'?: TdpCkanListingType;
  }

  interface IntrinsicElements {
    'tdp-ckan-connector': TdpCkanConnector;
    'tdp-ckan-dataset': TdpCkanDataset;
    'tdp-ckan-listing': TdpCkanListing;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'tdp-ckan-connector': LocalJSX.TdpCkanConnector & JSXBase.HTMLAttributes<HTMLTdpCkanConnectorElement>;
      'tdp-ckan-dataset': LocalJSX.TdpCkanDataset & JSXBase.HTMLAttributes<HTMLTdpCkanDatasetElement>;
      'tdp-ckan-listing': LocalJSX.TdpCkanListing & JSXBase.HTMLAttributes<HTMLTdpCkanListingElement>;
    }
  }
}


